### ISSUE TITLE
Interrupt channellist refresh while selection is open

### ISSUE THREAD

**Issue by Tommy-LSA** [acomminos/Plumble-Legacy#64] opened 2013-01-31 07:48 UTC
Hi,

If I scroll through a long list of Channels the list jumps up to top if the list get refreshed. It is not possible to reach the end of a long list. So if the dropdown channellist is open the refresh should be interrupted.

**Comment by Tommy-LSA** [comment] 2013-02-12 08:17
It seems that the refresh occurs on each logon/logoff of an user on the server. So you might not see this issue on silent or low frequented servers

**Comment by Zuko** [comment] 2013-02-12 09:25
Yes, I can confirm this.
ICS 4.0.4

**Comment by acomminos** [comment] 2013-02-17 00:36
Hi, thanks for the report. I haven't been able to work on Plumble recently due to my main PC's video card failing, but now that I've got my PC up and running, fixing this issue and then releasing upstream to the Play Store is my top priority.

**Comment by Zuko** [comment] 2013-02-17 00:43
good, let me know when it will be ready for translation

btw. "muted" and "muted and deafened" isn't translated in notification bar

2013/2/17 Andrew Comminos notifications@github.com

**Comment by acomminos** [comment] 2013-02-17 03:53
Kind of fixed in upstream. Unfortunately, there is no way to update the channel spinner for add/remove operations, so we're stuck with resetting the adapter whenever a channel is added or removed. Update operations work fine now though. Closing, will re-open if I find a way to accomplish add/remove updates.

**Closed as completed by acomminos** 2013-02-17 03:53 UTC

**Comment by acomminos** [comment] 2013-02-17 04:11
@Zuko, I isolated the notification strings for translation.
